export const BASE_URL = "http://localhost:3000";
export default{
    SIGN_UP : BASE_URL+"/user/create",
    SiGN_IN : BASE_URL+"/user/authUser",
    GETMOODOPTION : BASE_URL+"/mood/getMoodOptions",
    SUBMITMOOD  : BASE_URL + "/mood/create",
    QOUTE_CATEGORY : BASE_URL + "/quote/QouteCategory",
    Qoute_BY_CATEGORY : BASE_URL +"/quote/quoteByCategory",
    ADD_POSE : BASE_URL + "/pose/create",
    POSE_CATEGORY : BASE_URL + "/pose/typeOfPose",
    POSE_by_type : BASE_URL + "/pose/list",
    FATCH_POSE_ID: (id) => `${BASE_URL}/pose/get/${id}`,
    CREATE_PERSONAL_PLANE : BASE_URL + "/personalPlan/create",
    Admin_Add_Routine : BASE_URL + "/routine/create",
    LIST_ROUTINE  : BASE_URL + "/routine/routineCategory",
    ROUTINE_GET_BY_ID : BASE_URL + "/routine/getById",
    ADD_TO_FAVORITE : BASE_URL + "/favorite/create",
    LIST_FAVORITE  : (userId) => `${BASE_URL}/favorite/list/${userId}`,
    UPDATE_PROFILE  : BASE_URL + "/user/profile",
    USER_ROUTINE_LIST : (userId) => `${BASE_URL}/favorite/routineList/${userId}`,
    FAVORITE_BY_ID : (id) => `${BASE_URL}/favorite/favorite/${id}`,
    USER_PERSONALROUTINE_LIST : (userId) => `${BASE_URL}/personalPlan/list/${userId}`,
    USER_QOUTE_LIST : (userId) =>`${BASE_URL}/favorite/favorite/quote/${userId}`,
    DELETE_FAV_QOUTE : (userId) =>`${BASE_URL}/favorite/delete/${userId}`,
    USER_FAV_POSE : (userId) => `${BASE_URL}/favorite/pose/${userId}`,
    USER_MOOD_HISTORY  : (userId) => `${BASE_URL}/mood/list/${userId}`,
    RONDOM_QOUTE : BASE_URL + "/quote/rondomQuote",
    FEEDBACK_BY_USER : (userId) => `${BASE_URL}/feedback/create/${userId}`,
    ADMIN_FEEDBACK_LIST : BASE_URL + "/feedback/getAllFeedback",
    APPROVE_FEEDBACK : (id) => `${BASE_URL}/feedback/feedBack-approve/${id}`,
    LIST_OF_APPROVE_LIST : BASE_URL + "/feedback/listOfApproveFeedback",
    MEDIDATION_CATEGORY_LIST : BASE_URL + "/medidation/category"
}